DH-3226 - Adapt react-native-video framework to play m3u8 playlist with oauth
ConnectedHomes/react-native-video pull request #1
Opened 2018-06-21 13:25 UTC by VyacheslavPogorelskiy

2018-06-21 13:55 UTC, desislava-staykova approved these changes
👍 with one small comment

2018-06-21 13:55 UTC, desislava-staykova commented on ios/RCTAssetResourceLoaderDelegate.m
> +    [request setValue:self.accessToken forKey: @"X-JWT-TOKEN"];
Maybe pass the key as well as the access token, in case the service is changed.

2018-06-21 18:37 UTC, badeleux requested changes

2018-06-21 18:37 UTC, badeleux commented on ios/RCTVideo.m
> +                                                                  @"AVURLAssetHTTPHeaderFieldsKey": @{oauthTokenKey: oauthToken}}];
AFAIK it used private API it will cause rejection, also there is no point adding resource loader delegate if we're keepign this ;)

2018-06-22 13:43 UTC, badeleux approved these changes

2018-06-22 13:43 UTC, merged